[package]
name = "tunm_timer"
version = "0.1.3"
authors = [ "tickbh <tickdream125@hotmail.com>" ]

description = "simple timer, 简易定时器"
repository = "https://github.com/tickbh/tunm"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["timer", "simple_event"]


[dependencies]
rbtree = "0.1"